site_name: Nextflow Symposium 2023
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
repo_url: https://github.com/workflows-community/nextflow-symposium
repo_name: workflows-community/nextflow-symposium
edit_uri: edit/main/docs/
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - md_in_html
